version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: .
    environment:
      - PORT=5000
    expose:
      - "5000"

  app2:
    build: .
    environment:
      - PORT=5000
    expose:
      - "5000"

  app3:
    build: .
    environment:
      - PORT=5000
    expose:
      - "5000"
